"""
module 2 — asr + ocr extraction  (v2 — multilingual translate mode)

KEY FIX (v2): uses whisper task="translate" for non-english videos.
  - hindi videos previously rendered CS terms in devanagari ("रिकर्जन" instead
    of "recursion"), making english regex patterns fail completely
  - translate mode converts all speech to english while preserving CS terminology
  - english videos are unaffected (translate ≈ transcribe for en)

dual-output: saves both transcript_original.json (native script) and
  transcript.json (english, used for concept extraction downstream)
"""

import json
import argparse
import re
from pathlib import Path

import whisper
from PIL import Image
import pytesseract


# ───────────────── asr ─────────────────


def detect_language(model, audio_path: Path) -> tuple[str, float]:
    """fast language detection using first 30s of audio."""
    audio = whisper.load_audio(str(audio_path))
    audio_30s = whisper.pad_or_trim(audio)
    mel = whisper.log_mel_spectrogram(audio_30s).to(model.device)
    _, probs = model.detect_language(mel)
    lang = max(probs, key=probs.get)
    return lang, probs[lang]


def run_asr(audio_path: Path, model_size: str = "small") -> list[dict]:
    """
    transcribe audio with whisper.

    for non-english: runs BOTH transcribe (original) and translate (english).
    for english: runs transcribe only (translate would be identity).

    returns: list of english segments for downstream processing.
    """
    transcript_path = audio_path.parent / "transcript.json"
    original_path = audio_path.parent / "transcript_original.json"
    lang_path = audio_path.parent / "detected_language.json"

    # cache check — if transcript.json exists AND lang_path exists,
    # it was generated by v2 (translate mode). reuse.
    if transcript_path.exists() and lang_path.exists():
        print(f"[m2a] using cached transcript: {transcript_path}")
        with open(transcript_path) as f:
            return json.load(f)

    print(f"[m2a] loading whisper model: {model_size}")
    model = whisper.load_model(model_size)

    # step 1: detect language (fast — only 30s of audio)
    detected_lang, lang_prob = detect_language(model, audio_path)
    print(f"[m2a] detected language: {detected_lang} (confidence: {lang_prob:.1%})")

    # save language metadata
    lang_meta = {"language": detected_lang, "confidence": round(lang_prob, 4)}
    with open(lang_path, "w") as f:
        json.dump(lang_meta, f, indent=2)

    # step 2: transcribe in original language
    print(f"[m2a] transcribing in original language...")
    result_orig = model.transcribe(str(audio_path), task="transcribe", verbose=False)
    original_segments = [
        {"start": s["start"], "end": s["end"], "text": s["text"].strip()}
        for s in result_orig["segments"]
    ]

    # save original transcript (for reference / documentation)
    with open(original_path, "w", encoding="utf-8") as f:
        json.dump(original_segments, f, ensure_ascii=False, indent=2)
    print(f"[m2a] original transcript: {len(original_segments)} segments -> {original_path}")

    # step 3: if non-english, translate to english
    if detected_lang != "en":
        print(f"[m2a] translating to english (source: {detected_lang})...")
        result_trans = model.transcribe(str(audio_path), task="translate", verbose=False)
        translated_segments = [
            {"start": s["start"], "end": s["end"], "text": s["text"].strip()}
            for s in result_trans["segments"]
        ]
        print(f"[m2a] translated transcript: {len(translated_segments)} segments")
    else:
        translated_segments = original_segments
        print(f"[m2a] english detected — no translation needed")

    # save english transcript as primary (used by m3-m6)
    with open(transcript_path, "w", encoding="utf-8") as f:
        json.dump(translated_segments, f, ensure_ascii=False, indent=2)

    # count language distribution in original
    en_count = sum(1 for s in original_segments
                   if re.search(r'[a-zA-Z]{3,}', s["text"]))
    native_count = len(original_segments) - en_count
    print(f"[m2a] original language mix: en={en_count}, "
          f"{detected_lang}={native_count} / {len(original_segments)} total")

    return translated_segments


# ───────────────── ocr ─────────────────


def _clean_ocr(text: str) -> str:
    text = re.sub(r'[^\w\s\-\>\<\=\+\(\)\[\]\{\}\.\,\;\:\'\"]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def _ocr_confidence(frame_path: Path) -> tuple[str, float]:
    """run tesseract and return (text, mean_confidence)."""
    try:
        img = Image.open(frame_path)
        data = pytesseract.image_to_data(img, lang="eng+hin",
                                         output_type=pytesseract.Output.DICT)
        words, confs = [], []
        for w, c in zip(data["text"], data["conf"]):
            c = int(c) if str(c).lstrip('-').isdigit() else -1
            if c > 0 and w.strip():
                words.append(w.strip())
                confs.append(c)

        if not confs:
            return "", 0.0

        text = " ".join(words)
        avg_conf = sum(confs) / len(confs)
        return text, avg_conf
    except Exception as e:
        print(f"[m2b] ocr error on {frame_path.name}: {e}")
        return "", 0.0


def _pick_best_ocr(frame_path: Path, iterations: int = 3) -> tuple[str, float]:
    """run ocr multiple times and keep the best-confidence result."""
    best_text, best_conf = "", 0.0
    for _ in range(iterations):
        text, conf = _ocr_confidence(frame_path)
        if conf > best_conf:
            best_text, best_conf = text, conf
    return best_text, best_conf


def run_ocr(frames_dir: Path, min_conf: float = 40.0) -> list[dict]:
    """ocr all frames, filter by confidence, return time-aligned segments."""
    ocr_path = frames_dir.parent / "ocr_raw.json"

    if ocr_path.exists():
        print(f"[m2b] using cached ocr: {ocr_path}")
        with open(ocr_path) as f:
            return json.load(f)

    frames = sorted(frames_dir.glob("*.jpg"))
    print(f"[m2b] running ocr on {len(frames)} frames (min_conf={min_conf})")

    segments = []
    prev_text = ""

    for frame_path in frames:
        text, conf = _pick_best_ocr(frame_path, iterations=3)

        if conf < min_conf:
            continue

        cleaned = _clean_ocr(text)
        if not cleaned or len(cleaned) < 5:
            continue

        # dedup consecutive identical text
        if cleaned == prev_text:
            continue
        prev_text = cleaned

        # extract timestamp from frame filename: frame_00042.jpg -> t=42s
        match = re.search(r'(\d+)', frame_path.stem)
        t = float(match.group(1)) if match else 0.0

        segments.append({
            "start": t,
            "end": t + 1.0,
            "text": cleaned,
            "source": "ocr",
            "confidence": round(conf, 1),
        })

    with open(ocr_path, "w", encoding="utf-8") as f:
        json.dump(segments, f, ensure_ascii=False, indent=2)

    print(f"[m2b] ocr extracted {len(segments)} segments (filtered from {len(frames)} frames)")
    return segments


# ───────────────── alignment ─────────────────


def align_segments(asr_segments: list[dict], ocr_segments: list[dict]) -> list[dict]:
    """merge asr and ocr segments into a single time-sorted list."""
    aligned_path = None  # set by caller

    combined = []
    for s in asr_segments:
        combined.append({
            "start": s["start"],
            "end": s["end"],
            "text": s["text"],
            "source": "asr",
        })

    for s in ocr_segments:
        combined.append({
            "start": s["start"],
            "end": s["end"],
            "text": s["text"],
            "source": "ocr",
            "confidence": s.get("confidence", 0),
        })

    combined.sort(key=lambda x: x["start"])
    return combined


# ───────────────── main ─────────────────


def run(audio_path: str, frames_dir: str, model_size: str = "small") -> dict:
    audio_path = Path(audio_path)
    frames_dir = Path(frames_dir)
    out_dir = audio_path.parent

    asr_segments = run_asr(audio_path, model_size=model_size)
    ocr_segments = run_ocr(frames_dir)
    aligned = align_segments(asr_segments, ocr_segments)

    aligned_path = out_dir / "aligned_segments.json"
    with open(aligned_path, "w", encoding="utf-8") as f:
        json.dump(aligned, f, ensure_ascii=False, indent=2)

    print(f"[m2] aligned {len(aligned)} segments "
          f"(asr={len(asr_segments)}, ocr={len(ocr_segments)})")

    return {
        "n_asr_segments": len(asr_segments),
        "n_ocr_segments": len(ocr_segments),
        "n_aligned": len(aligned),
        "aligned_path": str(aligned_path),
        "detected_language": _read_lang_meta(out_dir),
    }


def _read_lang_meta(out_dir: Path) -> str:
    lang_path = out_dir / "detected_language.json"
    if lang_path.exists():
        with open(lang_path) as f:
            return json.load(f).get("language", "unknown")
    return "unknown"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("audio_path")
    parser.add_argument("frames_dir")
    parser.add_argument("--model", default="small")
    args = parser.parse_args()
    print(run(args.audio_path, args.frames_dir, args.model))
